server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Vue Router — toujours servir index.html pour les routes SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Pas de cache sur index.html
    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    # Cache long sur les assets vite (hash dans le nom)
    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
